The word "communication" has its root in the Latin verb "communicare", which means "to share" or "to make common".[1] Communication is usually understood as the transmission of information:[2][3][4] a message is conveyed from a sender to a receiver using some medium, such as sound, written signs, bodily movements, or electricity.[5][6][7] Sender and receiver are often distinct individuals but it is also possible for an individual to communicate with themselves. In some cases, sender and receiver are not individuals but groups like organizations, social classes, or nations.[5] In a different sense, the term "communication" refers to the message that is being communicated or to the field of inquiry studying communicational phenomena.[2][4]

The precise characterization of communication is disputed. Many scholars have raised doubts that any single definition can capture the term accurately. These difficulties come from the fact that the term is applied to diverse phenomena in different contexts, often with slightly different meanings.[8][9] The issue of the right definition affects the research process on many levels. This includes issues like which empirical phenomena are observed, how they are categorized, which hypotheses and laws are formulated as well as how systematic theories based on these steps are articulated.[10]

Some definitions are broad and encompass unconscious and non-human behavior.[11] Under a broad definition, many animals communicate within their own species and flowers communicate by signaling the location of nectar to bees through their colors and shapes.[5][12] Other definitions restrict communication to conscious interactions among human beings.[13][5] Some approaches focus on the use of symbols and signs while others stress the role of understanding, interaction, power, or transmission of ideas. Various characterizations see the communicator's intent to send a message as a central component. In this view, the transmission of information is not sufficient for communication if it happens unintentionally.[13][14] A version of this view is given by philosopher Paul Grice, who identifies communication with actions that aim to make the recipient aware of the communicator's intention.[15] One question in this regard is whether only successful transmissions of information should be regarded as communication.[16] For example, distortion may interfere with and change the actual message from what was originally intended.[6] A closely related problem is whether acts of deliberate deception constitute communication.[17]


The word "communication" has its root in the Latin verb "communicare", which means "to share" or "to make common".[1] Communication is usually understood as the transmission of information:[2][3][4] a message is conveyed from a sender to a receiver using some medium, such as sound, written signs, bodily movements, or electricity.[5][6][7] Sender and receiver are often distinct individuals but it is also possible for an individual to communicate with themselves. In some cases, sender and receiver are not individuals but groups like organizations, social classes, or nations.[5] In a different sense, the term "communication" refers to the message that is being communicated or to the field of inquiry studying communicational phenomena.[2][4]

The precise characterization of communication is disputed. Many scholars have raised doubts that any single definition can capture the term accurately. These difficulties come from the fact that the term is applied to diverse phenomena in different contexts, often with slightly different meanings.[8][9] The issue of the right definition affects the research process on many levels. This includes issues like which empirical phenomena are observed, how they are categorized, which hypotheses and laws are formulated as well as how systematic theories based on these steps are articulated.[10]

Some definitions are broad and encompass unconscious and non-human behavior.[11] Under a broad definition, many animals communicate within their own species and flowers communicate by signaling the location of nectar to bees through their colors and shapes.[5][12] Other definitions restrict communication to conscious interactions among human beings.[13][5] Some approaches focus on the use of symbols and signs while others stress the role of understanding, interaction, power, or transmission of ideas. Various characterizations see the communicator's intent to send a message as a central component. In this view, the transmission of information is not sufficient for communication if it happens unintentionally.[13][14] A version of this view is given by philosopher Paul Grice, who identifies communication with actions that aim to make the recipient aware of the communicator's intention.[15] One question in this regard is whether only successful transmissions of information should be regarded as communication.[16] For example, distortion may interfere with and change the actual message from what was originally intended.[6] A closely related problem is whether acts of deliberate deception constitute communication.[17]


